# NETWORK:
#   USE_PCD: True
#   UP_TYPE:  graph_mlp
#   ADJ_TYPE: laplacian

NETWORK:
  USE_PCD: True
  UP_TYPE:  graph_mlp
  ADJ_TYPE: adj
  PCD_LAST: True #True, False
  PRN_PRETRAINED: True
  PRN_TRAINED: True

LOSS:
  MID_LOSS: True
  MID_EDGE_LOSS: False